### ISSUE TITLE
Get Step Count

### ISSUE THREAD

**Issue by bradbamford** [etheriau/SamsungHealthForXamarin#2]
Trying to recreate the sample project "[SimpleHeath](https://developer.samsung.com/health/android/sample/simple-health.html)" from the Samsung SDK.

How do we use the **HealthDataStore.ConnectionListener**?
In SamsungHealthForXamarin, I'm only seeing an interface "HealthDataStore.IConnectionListener", do we have to role our own ConnectionListener?

Or is there a simpler way to get a daily step count?

**Comment by etheriau** [comment]
The easiest way to get Step Counts is to adapt the sample from https://developer.samsung.com/health/android/sample/step-diary.html to the C# version -- most of that is very straight forward since the C# wrapper is very similar.
